import type { Config, Permissions } from '../types';

export const DEFAULT_PERMISSIONS: Permissions = {
	allow: [
		'^ls\\b',
		'^cat\\b',
		'^head\\b',
		'^tail\\b',
		'^less\\b',
		'^more\\b',
		'^grep\\b',
		'^find\\b',
		'^pwd\\b',
		'^whoami\\b',
		'^date\\b',
		'^uname\\b',
		'^hostname\\b',
		'^df\\b',
		'^free\\b',
		'^du\\b',
		'^wc\\b',
		'^sort\\b',
		'^uniq\\b',
		'^cut\\b',
		'^tr\\b',
		'^true\\b',
		'^false\\b',
		'^test\\b',
		'^echo\\b',
		'^base64\\b',
		'^stat\\b',
		'^file\\b',
		'^which\\b',
		'^type\\b',
		'^readlink\\b',
		'^realpath\\b',
		'^dirname\\b',
		'^basename\\b',
		'^\\s*$',
		'^cd\\b',
		'^export\\b',
		'^alias\\b',
		'^source\\b',
		'^\\.\\s',
		'^\\[\\s',
		'^\\[\\[',
	],
	deny: [
		'^rm\\s+.*-.*rf.*|^rm\\s+.*-.*fr.*|^rm\\s+-[a-z]*rf|^rm\\s+-[a-z]*fr|^rm\\s+-[a-z]*r[a-z]*f|^rm\\s+-[a-z]*f[a-z]*r|^rm\\s+-[a-z]*r\\s+-[a-z]*f|^rm\\s+-[a-z]*f\\s+-[a-z]*r|^rm\\s+-[a-z]*ri|^rm\\s+-[a-z]*ir',
		'^rm\\s+.*-[a-z]*f[a-z]*r',
		'^rm\\s+.*-[a-z]*r[a-z]*i',
		'^rm\\s+.*-[a-z]*i[a-z]*r',
		'^cp\\s+.*-[a-z]*r',
		'^mv\\s+.*-[a-z]*r',
		'^\\bdd\\b',
		'^\\bmkfs\\b',
		'^\\bfdisk\\b',
		'^\\bchmod\\b',
		'^\\bchown\\b',
		'^\\bsudo\\b',
		'^\\bsu\\b',
		'^>\\s*/etc/|^>\\s*/root/|^>\\s*/boot/|^>\\s*/sys/|^>\\s*/proc/|^>\\s*/dev/|^>\\s*/$|^>>\\s*/etc/|^>>\\s*/root/|^>>\\s*/boot/|^>>\\s*/sys/|^>>\\s*/proc/|^>>\\s*/dev/|^>>\\s*/$',
		'^>>\\s*/',
		'^tee\\s+.*\\s*/',
		'^echo\\s+.*>\\s*/',
		'^python\\w*\\s+.*-c\\s+',
		'^node\\s+.*-e\\s+',
		'^bash\\s+.*-c\\s+',
		'^sh\\s+.*-c\\s+',
		'^zsh\\s+.*-c\\s+',
		'^perl\\s+.*-e\\s+',
		'^ruby\\s+.*-e\\s+',
		'^php\\s+.*-r\\s+',
		'^\\beval\\b',
		'^\\bexec\\b',
		'^\\bsystem\\b',
		'^\\bkill\\b',
		'^\\bfuser\\b',
		'^\\bpkill\\b',
		'^\\bkillall\\b',
		'^\\bshred\\b',
		'^\\bnc\\b',
		'^\\bncat\\b',
		'^\\bnmap\\b',
		'^\\bwget\\b',
		'^\\bcurl\\b',
		'^\\bssh\\b',
		'^\\bscp\\b',
		'^\\bsftp\\b',
	],
	ask: [
		'^rm\\s+\\S+',
		'^cp\\s+\\S+',
		'^mv\\s+\\S+',
		'^>\\s*[^/]',
		'^>>\\s*[^/]',
		'^\\|\\s*tee\\b',
		'^tee\\s+\\S+',
		'^echo\\s+.*>\\s+',
		'^printf\\s+.*>\\s+',
	],
};

export const DEFAULT_CONFIG: Config = {
	mode: 'read-only',
	shortcut: 'shift+tab',
	permissions: { ...DEFAULT_PERMISSIONS },
};
